"""2-delivery-state

Revision ID: 2aba9462f971
Revises: ecec098e7ae6
Create Date: 2026-09-10 17:20:38.353837

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "2aba9462f971"
down_revision: Union[str, Sequence[str], None] = "ecec098e7ae6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
