"""2-delivery-state

Revision ID: 35077971478e
Revises: 2aba9462f971
Create Date: 2026-09-10 17:37:32.120475

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "35077971478e"
down_revision: Union[str, Sequence[str], None] = "2aba9462f971"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("forms", "telegram_chat_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "forms",
        sa.Column("telegram_chat_id", sa.BIGINT(), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
