"""2-delivery-state

Revision ID: 3d31aa2ddba6
Revises: 35077971478e
Create Date: 2026-09-10 17:48:34.452061

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "3d31aa2ddba6"
down_revision: Union[str, Sequence[str], None] = "35077971478e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
