"""2-delivery-state

Revision ID: ecec098e7ae6
Revises: 7dceede7c614
Create Date: 2026-09-10 17:19:59.011099

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "ecec098e7ae6"
down_revision: Union[str, Sequence[str], None] = "7dceede7c614"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
